### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: ReMafoX: Easy App Localization
email: remafox@fline.dev
description: Improved Xcode Localization workflow
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mobileapplandingpage.learn.uno" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
twitter_username: ReMafoX_App
github_username: Jeehut
author: Cihat G端nd端z
logo: assets/images/large-logo.png
twitter:
  username: ReMafoX_App
social:
  name: Cihat G端nd端z
  links:
    - https://twitter.com/Jeehut
    - https://www.facebook.com/sandoche
    - https://www.linkedin.com/in/sandoche
    - https://plus.google.com/+SandocheADITTANE
    - https://github.com/Jeehut

languages: ["en"]
ampdir: amp

github: https://github.com/FlineDev/ReMafoX-Website

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
