name: "ReMafoX: Easy App Localization"
description: Improved Xcode Translation Workflow
full_description: 'Improved Xcode Translation Workflow<br>
<br>With a lot of features:
<br>- Feature 1
<br>- Feature 2
<br>- Feature 3'
android:
iOS: https://apps.apple.com/us/app/remafox-easy-app-localization/id1605635026
web:
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
producthunt:
companies:
  - url: https://fline.dev
    image: androidpolice.png
  - url: https://fline.dev
    image: producthunt.png
