name: "ReMafoX: Easy App Localization"
description: Improved Xcode Localization workflow
full_description: 'Improved Xcode Localization workflow<br>
<br>With a lot of features:
<br>- Feature 1
<br>- Feature 2
<br>- Feature 3'
android:
iOS: App Store
web:
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
producthunt:
companies:
  - url: https://telegra.ph/Replace-this-link-07-23
    image: androidpolice.png
  - url: https://telegra.ph/Replace-this-link-07-23
    image: producthunt.png
